[package]
name = "webserver_rust"
version = "0.1.0"
authors = ["Adrian Brink <adrian@brink-holdings.com>"]

[dependencies]
nickel = "0.9.0"
rustc-serialize = "0.3.22"
postgres = "0.13.3"
diesel = "0.9.0"
diesel_codegen = { version = "0.9.0", features = ["postgres"] }
dotenv = "0.8.0"
